# vim: set ft=ansible
---
# Implement your Workload deployment tasks here
- set_fact:
    user_name: "user{{ user_num }}"

- set_fact:
    project_name: "opendatahub-{{ user_name }}"

- name: "Create the JupyterHub Single User ConfigMap for {{ user_name }}"
  k8s:
    namespace: "{{ project_name }}"
    definition: "{{ lookup('template', 'jupyterhub-single-user-profile-user.configmap.yaml.j2') }}"

- name: "Create the ImageStream for the notebook used in this workshop"
  k8s:
    state: present
    namespace: "{{ project_name }}"
    definition: "{{ lookup('template', 'workshop-notebook.imagestream.yaml.j2') }}"

##################################################
# ARGO WORKFLOW
##################################################
- name: Create the Argo Workflow Service Account
  k8s:
    state: present
    namespace: "{{ project_name }}"
    definition: "{{ lookup('template', 'argo-workflow.serviceaccount.yaml.j2') }}"

- name: Create the Argo Workflow Role
  k8s:
    state: present
    namespace: "{{ project_name }}"
    definition: "{{ lookup('template', 'argo-workflow.role.yaml.j2') }}"

- name: Create the Argo Workflow RoleBinding
  k8s:
    state: present
    namespace: "{{ project_name }}"
    definition: "{{ lookup('template', 'argo-workflow.rolebinding.yaml.j2') }}"
##################################################

- name: Create the ODH Custom Resource
  k8s:
    state: present
    namespace: "{{ project_name }}"
    definition: "{{ lookup('template', 'opendatahub_v1alpha1_opendatahub_cr.yaml.j2') }}"
  when: deploy_odh_cr

# Leave this as the last task in the playbook.
- name: "{{ user_name }} tasks complete"
  debug:
    msg: "{{ user_name }} Tasks completed successfully."
  when: not silent|bool
